USE MTG;
GO


ALTER TABLE A
ADD
CONSTRAINT PK_ArtistID PRIMARY KEY (ArtistID),
CONSTRAINT UK_Phone UNIQUE (Phone);


ALTER TABLE P
ADD
CONSTRAINT PK_ProjectID PRIMARY KEY (ProjectID);


ALTER TABLE C
ADD
CONSTRAINT PK_CardID Primary Key (CardID);

ALTER TABLE dbo.APC ADD
CONSTRAINT PK_ID PRIMARY KEY (ID, Ano, Pno, Cno),
CONSTRAINT FK_APC_A FOREIGN KEY (Ano) REFERENCES dbo.A (ArtistID),
CONSTRAINT FK_APC_P FOREIGN KEY (Pno) REFERENCES dbo.P (ProjectID),
CONSTRAINT FK_APC_C FOREIGN KEY (Cno) REFERENCES dbo.C (CardID);

GO